### ISSUE TITLE
document "the most trivial test suite"

### ISSUE THREAD

**Issue by AloisMahdal** [teemtee/fmf#13]
(Note: this is just a quick feedback from exploration of fmf; IOW I haven't read all docs and might be wrong in what I expect.)

I tried to get a trivial test suite (eg. just one test) working with fmf.  I'm struggling to find simplest possible working example.  My idea is, that if I have test suite like this:

    mysut
       '--- mytest1
                '---- test.sh

where *test.sh* is something my test harness understands, what should I do as very first step to make this test suite "fmf-compliant"?

(Note that at this point, calling `fmf` from *mysut* merely lists *mysut/mytest1*, which is not even correct--this is just an arbitrary folder; I can't see why fmf should care about it. Which is in fact a case of issue #12.)

Examples section on redthedocs.io was not very helpful; they show examples of *content* but don't provide answer as to what file should I create.

**Comment by psss** [comment]
FMF does not define the attributes or how they should be used. But I think it is a good idea to include a minimal example of a BeakerLib test to show how the metadata can look like for a single test: 2c633a22439bedff4397e988efc85ffbd6ddecdd
