### ISSUE TITLE
Fail to parse fmf files on s390x

### ISSUE THREAD

**Issue by bgoncalv** [teemtee/fmf#164]
The following error is raised when trying to parse an fmf file:

```
unacceptable character #x0000: control characters are not allowed
```

Example:

```
# git clone https://github.com/cockpit-project/cockpit-podman.git
# cd cockpit-podman/test/browser/
# fmf show
 ERROR  Failed to parse '/root/cockpit-podman/plans/all.fmf'.
unacceptable character #x0000: control characters are not allowed
  in "/root/cockpit-podman/plans/all.fmf", position 72
```

This problem was introduced on version `1.0.0`

Note:

replacing `YAML(typ="safe").load(datafile)` by `YAML().load(datafile)` seems to solve the problem.

**Comment by happz** [comment]
Maybe some issue with encoding? https://realpython.com/python-yaml/#load-a-document-from-a-string-a-file-or-a-stream

**Comment by lukaszachy** [comment]
I've found https://sourceforge.net/p/ruamel-yaml/tickets/417/ which might be connected.

**Comment by lukaszachy** [comment]
Another workaround is to f.read() first and load yaml from string.

```
>>> from ruamel.yaml import YAML
>>> with open('r.yml') as f:
...  YAML(typ='safe').load(f)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/tmp/a/aaa/lib64/python3.6/site-packages/ruamel/yaml/main.py", line 434, in load
    return constructor.get_single_data()
  File "/tmp/a/aaa/lib64/python3.6/site-packages/ruamel/yaml/constructor.py", line 119, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 701, in _ruamel_yaml.CParser.get_single_node
  File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event
ruamel.yaml.reader.ReaderError: unacceptable character #x0000: control characters are not allowed
  in "r.yml", position 16
>>> with open('r.yml') as f:
...  b = f.read()
...  YAML(typ='safe').load(b)
... 
{'a': {'b': 'c'}}
```

**Comment by lukaszachy** [comment]
OT but tmt is great - Having s390x Fedora on your laptop is as simple as `tmt run provision -h virtual --arch s390x` (sure, real command was a bit longer to have more output and use system session etc. but...)

**Comment by psss** [comment]
> Another workaround is to f.read() first and load yaml from string.

This sounds like an acceptable workaround.
