### ISSUE TITLE
Case-sensitivity of context adjusting is unclear

### ISSUE THREAD

**Issue by FrNecas** [teemtee/fmf#186]
The documentation doesn't mention anything about case-sensitivity. The current implementation is case-sensitive:

```
>>> fmf.Context(distro='rhel-7.9').matches('distro=rhel')
True
>>> fmf.Context(distro='rhel-7.9').matches('distro=RHEL')
False
```

The least thing we can do is document this.

It could possibly be useful to do case-insensitive matching. This could have multiple forms (hence the discuss label):
- case-insensitive value matching by default
- special case-insensitive operators
- flag in the adjust dict that specifies case-sensitivity (would probably default to the current state = case-sensitive)

Usefulness of the case-insensitivity: rhel vs RHEL, centos vs CentOS, etc.

**Comment by psss** [comment]
Summary from the hacking session:

* Keep `fmf` implementation case sensitive by default and document it
* Allow explicitly to ignore the case when calling `adjust()`
* Handle the lower case on the tmt side

The `tmt` part to be covered by teemtee/tmt/issues/1953.

**Comment by ivet1987** [comment]
@psss yes, that's the plan for this week but maybe I will need a little help :-D
