### ISSUE TITLE
Allow to use`--filter` for `name`

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/fmf#76]
As a User I want to be able to filter name by using fmf.filter so I have consistency with filter by attributes.

`fmf ls --filter tier:1` but `fmf ls --name /test/me`. 
I want be able to use `fmf ls --filter name:/test/me` as well

**Comment by psss** [comment]
The thing is that `name` can be an attribute name so we need to invent some special name which would not collide with possible attributes, perhaps something like `_name` or `fmf-name`?

**Comment by lukaszachy** [comment]
Allowing users to have mismatch in `--name` and `name` attribute? 
What can be possible use case and how one will call them? So for the artificial example
```yaml
/foo:
  name: bar
```
Where one will be able to `fmf ls --name foo --filter name:bar` Personally I think that it is highly confusing.

**Comment by psss** [comment]
So... do you suggest to use `name` insed a filter and in this way do not allow users using a `name` attribute?

**Comment by lukaszachy** [comment]
Yes, I suggest to reserve `name` attribute for fmf and don't allow users to modify it.
But keep `fmf --name` option, IMHO it is handy.

**Comment by psss** [comment]
So the final decision was to allow searching for node name by providing only the name in the literal, that is no `key: value` pair. This has been implemented in #219 and is ready for review.
